databases:
  - name: SpoHealBack
    ipAllowList: []

services:
  - type: web
    name: SpoHealBack
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: SpoHealBack
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false